# 指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js: 12.18.3

env:
 global:
   - URL_REPO: github.com/10veU/10veU.github.io.git

# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - master

# 设置缓存文件
cache:
  directories:
    - node_modules

#在构建之前安装hexo环境
before_install:
  - npm install -g hexo-cli

#安装git插件和搜索功能插件
install:
  - npm install

  # 设置git提交名，邮箱；替换真实token到_config.yml文件
before_script:
  - git config user.name "10veU"
  - git config user.email "xiaojie_wangxj@163.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  - sed -i "s/github_token/${Travis_token}/g" ./_config.yml

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 514084647@qq.com
  on_success: change
  on_failure: always